[package]
name = "avrora"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "avrora"
crate-type = ["cdylib"]

[dependencies]
apache-avro = "0.17.0"
pyo3 = "0.23.5"
