name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v4
        with:
          python-version: '3.7'

      - name: Install python dependencies
        run: make install-poetry install

      - name: Run linters
        run: make lint

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['3.7']
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.version }}

      - name: Install python dependencies
        run: make install-poetry install

      - name: Run test
        run: make test

